name: MyPy

on: [ push, pull_request ]


jobs:
  mypy:
    name: Run MyPy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pyside 6.6.3 has some issue in their .pyi files
          pip install PySide6==6.6.2
          pip install -r requirements.txt
          pip install mypy==1.10.0

      - name: Run MyPy
        run: |
          cd tagstudio
          mkdir -p .mypy_cache
          mypy --install-types --non-interactive 
          mypy --config-file ../pyproject.toml .
