name: run_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Add commit for testing or whatever

jobs:
  test:
    #timeout-minutes: 20
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pyside 6.6.3 has some issue in their .pyi files
          pip install PySide6==6.6.2
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest-mock==3.14.0

      - name: Run tests
        run: |
          pytest tagstudio/tests/core/test_tags.py
